module.exports = {
   'ACTIONS_EN_GB': {
      'CPR': 'If you are not trained in CPR, provide hands-only CPR. Put the person on his back on a firm surface. Kneel by his neck and shoulders. Place the heel of one hand over the center of his chest between the nipples. Place your other hand on top of the first hand. Keep elbows straight and position shoulders directly above your hands. Use your upper body weight as you push straight down on the chest at least 2 inches but no more than 2.4. Push hard at a rate of 100 to 120 compressions a minute, like the song by the bee gees, staying alive. Call emergency services. ',
      'heimlich maneuver': 'First, make sure the person is aware you will perform the maneuver. Stand behind the choker and wrap your arms around the waist of the choker. With one hand, make a fist. Wrap your other hand around your fist. Make a series of thrusts by pressing hard and quick into the abdomen. Pull inward and upward. It should feel like you are trying to lift the person off the ground. If this does not work, deliver a few blows to the back bewteen the shoulder blades with the heel of your hand. Call emergency services. '
   },
   'ACTIONS_EN_US': {
      'CPR': 'If you are not trained in CPR, provide hands-only CPR. Put the person on his back on a firm surface. Kneel by his neck and shoulders. Place the heel of one hand over the center of his chest between the nipples. Place your other hand on top of the first hand. Keep elbows straight and position shoulders directly above your hands. Use your upper body weight as you push straight down on the chest at least 2 inches but no more than 2.4. Push hard at a rate of 100 to 120 compressions a minute, like the song by the bee gees, staying alive. Call emergency services. ',
      'heimlich maneuver': 'First, make sure the person is aware you will perform the maneuver. Stand behind the choker and wrap your arms around the waist of the choker. With one hand, make a fist. Wrap your other hand around your fist. Make a series of thrusts by pressing hard and quick into the abdomen. Pull inward and upward. It should feel like you are trying to lift the person off the ground. If this does not work, deliver a few blows to the back bewteen the shoulder blades with the heel of your hand. Call emergency services. '

   }
};
